use BDJURIDICO

CREATE TABLE TIPOPESSOA (
TIPID INT IDENTITY (1,1) PRIMARY KEY,
TIPDESCRICAO VARCHAR (100) NOT NULL,
)

CREATE TABLE PROCESSO (
PROID INT IDENTITY (1,1) PRIMARY KEY,
PRORELATO VARCHAR (1000) NOT NULL,
PRODATA DATETIME 
)

CREATE TABLE PESSOA (
PESID INT IDENTITY (1,1) PRIMARY KEY,
PESNOME VARCHAR(100) NOT NULL,
PESCPF VARCHAR (20) NOT NULL,
PESCNPJ VARCHAR(20),
PESSEXO CHAR (100) NOT NULL
)

CREATE TABLE PESSOAPROCESSO(
PESID INT NOT NULL,
PROID INT NOT NULL,
TIPID INT NOT NULL,
DATAVINCULO DATETIME
CONSTRAINT PK_PESSOAPROCESSO PRIMARY KEY (PESID,PROID),

CONSTRAINT FK_PESSOAPROCESSO_PESSOA FOREIGN KEY (PESID)
REFERENCES PESSOA(PESID),
CONSTRAINT FK_PESSOAPROCESSO_PROID FOREIGN KEY (PROID)
REFERENCES PROCESSO(PROID),
CONSTRAINT FK_PESSOAPROCESSO_TIPO FOREIGN KEY (TIPID)
REFERENCES TIPOPESSOA(TIPID),
)

INSERT PESSOA (PESNOME, PESCPF, PESCNPJ,PESSEXO)
VALUES ('ANA', '123', NULL, 'FEMININO')
GO
INSERT TIPOPESSOA VALUES ('REU')
GO
INSERT PROCESSO VALUES ('GOTA SERENA', GETDATE())
SELECT * FROM PESSOA 
SELECT * FROM PROCESSO 
SELECT * FROM TIPOPESSOA
INSERT PESSOAPROCESSO VALUES (1,1,1, GETDATE())
INSERT PESSOAPROCESSO VALUES (1,2,1, GETDATE())
